create table whois_record_flat_simple (
`whois_record_flat_id` bigint(20) NOT NULL AUTO_INCREMENT,
`domainName` varchar(256),
`registrarName` varchar(512),
`contactEmail` varchar(256),
`whoisServer` varchar(512),
`nameServers` varchar(256),
`createdDate` varchar(256),
`updatedDate` varchar(256),
`expiresDate` varchar(256),
`standardRegCreatedDate` varchar(256),
`standardRegUpdatedDate` varchar(256),
`standardRegExpiresDate` varchar(256),
`status` text,
`Audit_auditUpdatedDate` varchar(256),
`registrant_email` varchar(256),
`registrant_name` varchar(256),
`registrant_organization` varchar(256),
`registrant_street1` varchar(256),
`registrant_street2` varchar(256),
`registrant_street3` varchar(256),
`registrant_street4` varchar(256),
`registrant_city` varchar(64),
`registrant_state` varchar(256),
`registrant_postalCode` varchar(45),
`registrant_country` varchar(45),
`registrant_fax` varchar(45),
`registrant_faxExt` varchar(45),
`registrant_telephone` varchar(45),
`registrant_telephoneExt` varchar(45),
`administrativeContact_email` varchar(256),
`administrativeContact_name` varchar(256),
`administrativeContact_organization` varchar(256),
`administrativeContact_street1` varchar(256),
`administrativeContact_street2` varchar(256),
`administrativeContact_street3` varchar(256),
`administrativeContact_street4` varchar(256),
`administrativeContact_city` varchar(64),
`administrativeContact_state` varchar(256),
`administrativeContact_postalCode` varchar(45),
`administrativeContact_country` varchar(45),
`administrativeContact_fax` varchar(45),
`administrativeContact_faxExt` varchar(45),
`administrativeContact_telephone` varchar(45),
`administrativeContact_telephoneExt` varchar(45),
`registrarIANAID` varchar(45),
 primary key (`whois_record_flat_id`)
)ENGINE=InnoDB ROW_FORMAT=COMPRESSED AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
