all:
	echo "Doing nothing. Please specify what to do."

deploy_webnx2:
	cp countries /var/www/vhosts/domainwhoisdatabase.com/whois_database/v19/docs/
	cp countries /var/www/vhosts/domainwhoisdatabase.com/whois_database/v20/docs/
	cp countries /var/www/vhosts/domainwhoisdatabase.com/domain_list_quarterly/v6/docs/
	cp countries /var/www/vhosts/domainwhoisdatabase.com/domain_list_quarterly/v5/docs/

deploy_webnx3:
	cp *.sh /var/www/vhosts/bestwhois.org/domain_name_data/docs/loader_scripts/csv/schema/.
	cp *.sql /var/www/vhosts/bestwhois.org/domain_name_data/docs/loader_scripts/csv/schema/.
	cp README /var/www/vhosts/bestwhois.org/domain_name_data/docs/loader_scripts/csv/schema/.
	cp countries /var/www/vhosts/bestwhois.org/domain_name_data/docs/.
